### ISSUE TITLE
RVIZ Transform error Base_link and Camera_link

### ISSUE THREAD

**Issue by Tondy** [ros-visualization/rviz#1033]
am working on a differential drive robot with two motor wheels with encoders and caster wheels. The robot also has a intel realsense depth camera.

When I launch RVIZ : Thee Global option > Fixed frame is set to Base_link and shows all the transforms for the differential driver nodes. But an error appears for the Depth camera nodes with message saying :

No transform from Camera_depth_frame to baselink

No transform from Camera_depth_optical_frame to baselink

No transform from Camera_link to baselink

No transform from Camera_rgb_frame to baselink

If I change the Global option > fixed frame to Camera_link I can see all the transforms for the depth camera but now the differential drive transforms are now not available

Hope you can help.

**Comment by wjwwood** [comment]
rviz requires transform information to be published on the `/tf` topic in order to render data in different frames. That's what the error messages are about. You're asking rviz to render in the `base_link` (I'm guessing that's what you mean, but it's inconsistent throughout your issue description) but the data is in a different frame and rviz doesn't have the information necessary to transform the data into the fixed frame.

Please ask questions like this on http://answers.ros.org, and see our support page: http://wiki.ros.org/Support
