### ISSUE TITLE
MarkerDisplay limits you to 100 Markers

### ISSUE THREAD

**Issue by mogumbo** [ros-visualization/rviz#1135]
As far as I can tell, you should be able to have more than 100 Markers in your scene by doing Add->Marker in RViz and increasing the Queue Size above 100. However, this appears to have no effect. I can only see 100 Markers in RViz. What does work is to hardcode a new default size for queue_size_property_ in the MarkerDisplay constructor.

**Comment by wjwwood** [comment]
If you're sending many markers at once (only time the queue size is important) then you should probably use a MarkerArray. Also when you want to scale up things past hundreds you should try to use a "list" style marker rather than lots of individual markers if you are able, see:

http://wiki.ros.org/rviz/DisplayTypes/Marker#Rendering_Complexity_Notes

Either way, the property should work as you've described (it doesn't make sense that hard coding a new value works but changing the property does not).

**Comment by mogumbo** [comment]
Thank you for the tips. Trying MarkerArray was on my todo list as a possible solution, but I'm not familiar with "list" style markers yet. I'll investigate those too.
