### ISSUE TITLE
librviz display topic

### ISSUE THREAD

**Issue by XuxinDoubleWang** [ros-visualization/rviz#1150]
Hello everyone, 
I am trying to use librviz to display other topic into a Custom GUI.
I follow this tutorial [http://docs.ros.org/indigo/api/librviz_tutorial/html/index.html](url)
However, grid is too simple to make sense in details.
I try to add my own rviz::Display* point_   in myviz.h,
and the following code in myviz.cpp:

  point_ = manager_->createDisplay("rviz/PointCloud2", "PointCloud2", true);
  ROS_ASSERT( point_ != NULL );
  point_->subProp("Topic")->setValue("/kinect2/sd/points");
  point_->subProp("Style")->setValue("Flat Squares");
  point_->setFixedFrame("kinect2_ir_optical_frame");

There is no error shows when I compiled. However, it only shows the adjusted grid (in tutorial) without my point cloud.

Does anyone have some experience about that?

Any ideas are appreciated!!!

**Comment by dhood** [comment]
Hi @XuxinDoubleWang, you may have resolved your issue already, but:

I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rationale for asking all kinds of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
