### ISSUE TITLE
Pluginlib/RViz set library search path?

### ISSUE THREAD

**Issue by jvogtherr** [ros-visualization/rviz#1187]
I am having an issue with RViz/Pluginlib not finding a certain library. I tried asking on ROSAnswers, but to no success yet. 

I want to use a lib that depends on MPI. I can use this lib in any ROS node and it works perfectly fine, however in RViz it doesnt. I can include and build the lib and start RViz, but when the Plugin is loaded, Pluginlib throws an error:

> [ERROR] [1516723469.202952222]: PluginlibFactory: The plugin for class 'rviz_mesh_plugin/TexturedMesh' failed to load. Error: Failed to load library /workspace/devel/lib//librviz_mesh_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /workspace/devel/lib//librviz_mesh_plugin.so: undefined symbol: _ZN3MPI3Win4FreeEv)

It seems like Pluginlib cannot locate the MPI package and throws an undefined symbol error (with the symbol being MPI_Win::Free). Since this library runs on any regular ROS package, I assume it has to be an issue with RViz/Pluginlib's own include path for libraries. Is there a way for me to configure the path where RViz/Pluginlib searches for libraries? Then I could point it directly to where MPI is located. 

Thank you for any suggestions or ideas!

**Comment by wjwwood** [comment]
There's nothing special about how this works with rviz. It uses the `LD_LIBRARY_PATH` or the information in the shared library to load dependent ones (you can use `ldd` to see).

My guess is that when ever you link this library into a program elsewhere, those programs are also linked against something that has that symbol. So the symbol is satisfied, but when loading just the library, rviz doesn't have that symbol so it fails.

I suggest you try a simple `dlopen` example which just loads the shared library. Until that works, rviz will probably not work. For example:

http://www.tldp.org/HOWTO/html_single/C++-dlopen/#loadingfunctions

I'll close this for now, because I don't believe rviz or pluginlib/class_loader should change anything. I can reopen if that's not the case.
