### ISSUE TITLE
rviz Camera and Image Displays exhibit one-off display error on edges

### ISSUE THREAD

**Issue by skohlbr** [ros-visualization/rviz#1253]
I'm on 16.04/Kinetic/latest .debs for rviz. We noticed that there seems to be a bug that leads both Image and Camera Displays to show the first row of image pixels at the bottom, or the first column on the right side (or at least that's how it looks). See the following screenshots:

First row replicated at bottom:
![rviz_one_off_issue](https://user-images.githubusercontent.com/205963/41206941-df304baa-6d0c-11e8-8d89-c5f1bd6fca46.png)

First column replicated at right side:
![rviz_one_off_issue_vertical](https://user-images.githubusercontent.com/205963/41206942-e56b90ec-6d0c-11e8-95cf-8580aae551dd.png)

As circled red there, it appears that image data from one side appears on the other side of the image.

**Comment by KenYN** [comment]
I've run into this too, and [just finished reported it on ROS Answers](https://answers.ros.org/question/338572/rviz-drawing-extra-pixel-on-left-and-right-of-image/).

**Comment by KenYN** [comment]
I wonder [if this is related](https://forums.ogre3d.org/viewtopic.php?t=52054#p358272)? I've not tried debugging yet, but I suspect the problem might be [around `image_display.ccp` lines 221-228](https://github.com/ros-visualization/rviz/blob/51227fab813a5e2534475e60bf573ee9540e399e/src/rviz/default_plugin/image_display.cpp#L221)?

**Comment by rhaschke** [comment]
I'm afraid that this is an issue deep in Ogre: rviz uses Ogre to render the image texture onto a rectangle attached to the scene. To maintain the correct image aspect ratio no matter what window aspect ratio is used, [this code](https://github.com/ros-visualization/rviz/blob/51227fab813a5e2534475e60bf573ee9540e399e/src/rviz/default_plugin/image_display.cpp#L216L229) scales and moves the rendering rectangle appropriately. This scaling introduces  the rendering artifacts in rviz. When using `rosrun rviz image_view`, the artifact is gone, because this small test application doesn't scale the image to maintain aspect ratio.
Closing as won't fix in rviz.
You could try to build against Ogre 1.12, which is supported in the noetic-devel branch.
