### ISSUE TITLE
Problem compiling "ogre_helpers/point_cloud.cpp" with GCC 8.1.1 on ArchLinux

### ISSUE THREAD

**Issue by ziokuroi** [ros-visualization/rviz#1254]
The error at "point_cloud.cpp:340"
`src/rviz/ogre_helpers/point_cloud.cpp:340:52: error: no matching function for call to ‘rviz::PointCloudRenderable::setMaterial(const String&)’
     (*it)->setMaterial(current_material_->getName());`
I googled, but found nothing about the problem.

**Comment by ziokuroi** [comment]
: ) maybe this is a dead project, fu*k ROS & fu*k linux

**Comment by Alessandro-Barbieri** [comment]
I have the same issue on gentoo

**Comment by rhaschke** [comment]
Which Ogre Version do you use? If it's new than 1.9.1, you should try the noetic-devel branch, which is prepared for Ogre 1.10 .. 1.12.

**Comment by Alessandro-Barbieri** [comment]
ogre-1.9.0
I opened a bug here
https://bugs.gentoo.org/710540

**Comment by rhaschke** [comment]
The error reported on gentoo.org differs from the one reported here. There seems to be a type conflict because Ogre was compiled with double precision, while on Ubuntu it's compiled with single precision.
You should replace suspicious hard-coded `float` types with `Ogre::Real` in rviz. Please file a PR with all these required changes.
