### ISSUE TITLE
Visualization bug on MacOS

### ISSUE THREAD

**Issue by dawnos** [ros-visualization/rviz#1268]
I'm trying to compile & run rviz (kinetic) on MacOS (High Sierra), just following [http://wiki.ros.org/kinetic/Installation/OSX/Homebrew/Source](url). After some minor modification, I successfully compile it. But when running, it get some problem:
![image](https://user-images.githubusercontent.com/2622870/42720485-13e6fe54-875a-11e8-8ff9-668d7c766f1e.png)

3/4 of the display area is red.

Does anyone meet the same problem? Any solution?

Thank you!

**Comment by rlober** [comment]
Not sure about the red, but the screen size issue is related to this: #1262

**Comment by dawnos** [comment]
Thanks @rlober  . #1262 looks similar. I've tried it as what you say, but it still not work (same as above):

![2018-07-15 11 36 07](https://user-images.githubusercontent.com/2622870/42762513-24367af6-8943-11e8-9401-05162a9d252e.jpg)
![2018-07-15 11 36 43](https://user-images.githubusercontent.com/2622870/42762514-24b001fa-8943-11e8-9e78-6e58a0f27baa.jpg)
![2018-07-15 11 37 12](https://user-images.githubusercontent.com/2622870/42762515-251cdf5a-8943-11e8-8a3c-88a201804097.jpg)

**Comment by rlober** [comment]
Can you try adding `QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);` [here](https://github.com/ros-visualization/rviz/blob/melodic-devel/src/rviz/main.cpp#L37) ?

**Comment by meyerj** [comment]
Same problem here. I also tried adding the line proposed in https://github.com/ros-visualization/rviz/issues/1268#issuecomment-405866942, without success. But it's not a big issue because the red area disappears and the scale becomes correct as soon as you move the camera or resize the window.

I am currently testing with rviz version 1.12.15 and Ogre 1.9 built from https://github.com/osrf/homebrew-simulation/blob/3ced67c30622d583d8df031dc7b91c5d8f6e7829/ogre1.9.rb on macOS Sierra.

**Comment by rhaschke** [comment]
Fixed in #1263.
