### ISSUE TITLE
show PointCloud2 normals in rviz  (ros-pkg ticket #4498)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#361]
Rviz doesn't currently have a good way to visualize point cloud normals, and it would be really nice if it did--it would probably be too expensive to show all normals, but having parameters for how sparse to make the arrows could make it reasonable.

trac data:
- Owner: **hersh**
- Reporter: **kaijenhsiao**
- Reported at: **Thu Oct 14 14:09:22 2010**
- URL: http://code.ros.org/trac/ros-pkg/ticket/4498

**Comment by ozaslan** [comment]
Hi. Is there any update on this? This looks like a reasonable request. 

I am not sure if we understand the question the same way: might hershwg be suggesting plotting normals already calculated and sitting in the normal_{x,y,z} fields of PointCloud2 message, rather than RViz calculating them and then plotting? So, RViz will not make any decisions on how to calculate them.

Thanks

**Comment by wjwwood** [comment]
@ozaslan nothing is planned (issue closed), but I see what you mean, it wasn't at all clear if the normals should be calculated first or if the normals are already in the data and should be visualized.

If you want, please open a new ticket that requests this particular feature (visualizing existing normals data). However, don't expect it to just be implemented since it's a reasonable request, instead consider organizing an effort to provide a pull request with this feature.

**Comment by hanzheteng** [comment]
We have made an attempt on this topic and created a customized rviz plugin to display the normal field of the point cloud (type `sensor_msgs::PointCloud2`). It is assumed that normals are already computed ahead of time.

Our repository: https://github.com/UCR-Robotics/pointcloud2_normal_rviz_plugin

This plugin visualizes the normal field only, and needs to be used along with the default PointCloud2 plugin to display points in the point cloud.
