### ISSUE TITLE
rviz does not show camera image in camera display  (ros-pkg ticket #4808)

### ISSUE THREAD

**Issue by hershwg** [ros-visualization/rviz#376]
I attached the old display_config file with which it did not work to show images from any camera topic in a camera display.

trac data:
- Owner: **hersh**
- Reporter: **jbohg**
- Reported at: **Mon Feb 21 15:17:34 2011**
- URL: http://code.ros.org/trac/ros-pkg/ticket/4808

**Comment by caylaXu** [comment]
i am stuck with a error in rviz which states that " no image received" in status field under camera. I am using iball usb_cam. I tried all the camera drivers like gscam,uvc_camera,usb_cam . But , this error still exists . [Note: The image window does not produce any error. but camera window only produce this error .] Please give me any suggestions

**Comment by wjwwood** [comment]
@caylaXu the camera display creates a new 3D render display in the tf frame of the image and renders the image on top of that display. To do this it requires the corresponding `camera_info` topic so that it can rectify the image. If your image topic doesn't have a corresponding `camera_info` topic, that might be why the "Image display" works but the "Camera display" does not. See: http://wiki.ros.org/rviz/DisplayTypes and http://wiki.ros.org/image_pipeline/CameraInfo

Also, I do not believe this is an appropriate place to ask the question. Please direct further questions to answers.ros.org, and see: http://wiki.ros.org/Support When and if you find an actual bug, then you can open an issue here.
